language: python
git:
  depth: 10
  quiet: true
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      python: "3.7"
      script:
        - set -v  # print commands as they're executed
        - set -e  # fail and exit on any command erroring
        - rm -rf *.egg-info/
        - pylint --jobs=2 --rcfile=pylintrc *.py
        - pylint --jobs=2 --rcfile=pylintrc */
python:
  - "3.7"
install:
  - set -v  # print commands as they're executed
  - set -e  # fail and exit on any command erroring
  # Ensure that the base dependencies are sufficient for a full import.
  # Install backend and test dependencies.
  - pip install -q -e .[tests]
  - python -c "import uncertainty_baselines as ub"

script:
  - set -v  # print commands as they're executed
  - set -e  # fail and exit on any command erroring
  # Skip the dataset tests because they are extremely long because they have to
  # download every single dataset.
  - python -m unittest -v *_test.py
  - python -m unittest -v models/*_test.py
